version: '3'
services:
  site1:
    build:
      context: ./site1
      dockerfile: ../Dockerfile.site
    ports:
      - "8085:80"
    volumes:
      - ../css:/usr/share/nginx/html/css

  site2:
    build:
      context: ./site2
      dockerfile: ../Dockerfile.site
    ports:
      - "8086:80"
    volumes:
      - ../css:/usr/share/nginx/html/css

  load_balancer:
    image: nginx:latest
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:80"
    depends_on:
      - site1
      - site2
